### ISSUE TITLE
Rollback didn't work within migration order

### ISSUE THREAD

**Issue by erashdan** [okv/east#81] opened 2021-07-14 09:59 UTC
Hi,

When we make a rollback it didn't work within migration order here an example
```
Migrate "1_create_users_table"
Migration done
Migrate "2_create_products_table"
Migration done
Migrate "3_create_orders_table"
Migration done
```

And when we did a rollback 
```
Rollback "2_create_products_table"
Migration successfully rolled back
Rollback "1_create_users_table"
Migration successfully rolled back
Rollback "3_create_orders_table"
Migration successfully rolled back
```

How we can run a rollback within reversed migration order?

**Comment by okv** [comment] 2021-07-14 10:21
Hey! It should call migrations in a reverse order when it's rolling back. That's interesting, I will try to take a look at this on the weekend.

**Comment by erashdan** [comment] 2021-07-26 13:25
Hi @okv

any update?

**Comment by okv** [comment] 2021-07-26 20:20
Hi! Haven't checked it out yet. I've had a few busy weeks, sorry.

**Comment by okv** [comment] 2021-07-26 20:42
I'm looking at it right now though :smiley: 
Trying to reproduce it with the default adapter:

```sh
> east init
initialization successfully done, migration files will be stored at "/tmp/east/migrations"

> east create create_users_table
New migration "1_create_users_table" created at "/tmp/east/migrations/1_create_users_table.js"
> east create create_products_table
New migration "2_create_products_table" created at "/tmp/east/migrations/2_create_products_table.js"
> east create create_orders_table
New migration "3_create_orders_table" created at "/tmp/east/migrations/3_create_orders_table.js"

> east migrate
Target migrations:
	1_create_users_table
	2_create_products_table
	3_create_orders_table
Migrate "1_create_users_table"
Migration done
Migrate "2_create_products_table"
Migration done
Migrate "3_create_orders_table"
Migration done

> east rollback
Target migrations:
	3_create_orders_table
	2_create_products_table
	1_create_users_table
Rollback "3_create_orders_table"
Migration successfully rolled back
Rollback "2_create_products_table"
Migration successfully rolled back
Rollback "1_create_users_table"
Migration successfully rolled back
```
As you can see, I have no luck so far, the order is correct.
Could you help me to reproduce it?

Which adapter do you use?
Can you provide content of the `.eastrc`?
Your Node.js version?
Which OS do you use?
Any other relevant information that might be useful?

**Comment by okv** [comment] 2021-11-19 16:49
I'm closing this since there is no news. Feel free to open it again but please provide requested information (see above).

**Closed by okv** 2021-11-19 16:49 UTC
